sudo: required

language: node_js
node_js:
  - lts/*

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - ls
  - docker-compose up --build -d
  - cd frontend && yarn install --frozon-lockfile
  - cd .. && cd backend && yarn install --frozon-lockfile
  - cd .. && sudo locate libcrypto.so.1.0.0

script:
  - docker-compose up -d
  # - docker-compose exec frontend yarn test --watchAll=false
  # - docker-compose exec backend yarn test --watchAll=false
  - docker-compose down
