version: '3'

services:
  frontend:
    build: ./frontend
    image: 514445668943.dkr.ecr.ap-northeast-1.amazonaws.com/myapp-frontend:latest
    # command: 'yarn start'
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/myapp/frontend
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    tty: true

  backend:
    build: ./backend
    image: 514445668943.dkr.ecr.ap-northeast-1.amazonaws.com/myapp-backend:latest
    # command: 'yarn start'
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/myapp/backend
volumes:
  yarn-cache:
