version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: 'yarn start'
    ports:
      - '3000:3000'
      - '9099:9099' #Auth
      - '4000:4000' #Emulators
      - '9090:9090' #firestore
    volumes:
      - ./frontend:/myapp/frontend
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    tty: true

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: 'yarn start'
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/myapp/backend
    environment:
      CHOKIDAR_USEPOLLING: 1
volumes:
  yarn-cache:
