version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          command: docker-compose up
      - run:
          command: docker-compose exec frontend yarn test --watchAll=false
      - run:
          command: docker-compose exec backend yarn test --watchAll=false
      - run:
          command: docker-compose down
