version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: |
          echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
          echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run: |
          node -v
      - run: |
          nvm install v10
          node -v
          nvm alias default v10
      - run: |
          node -v
      - run:
          command: gpg --recv-key 78BD65473CB3BD13 && gpg -a --export 78BD65473CB3BD13 | sudo apt-key add -
      - run:
          command: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run:
          command: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - run:
          command: sudo apt-get update && sudo apt-get install yarn
      # - run:
      #     command: curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      # - run:
      #     command: sudo apt-get install -y nodejs npm
      # - run:
      #     command: sudo npm install n -g && sudo n stable && sudo apt purge -y nodejs npm
      - run:
          command: node -v
      - run:
          command: docker-compose up --build -d
      - run:
          command: cd frontend && yarn install --frozon-lockfile && ls
      - run:
          command: cd backend && yarn install --frozon-lockfile && ls
      - run:
          command: docker-compose up -d
      - run:
          command: docker-compose exec frontend yarn test --watchAll=false
      - run:
          command: docker-compose exec backend yarn test --watchAll=false
      - run:
          command: docker-compose down
