version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          command: gpg --recv-key 78BD65473CB3BD13 && gpg -a --export 78BD65473CB3BD13 | sudo apt-key add -
      - run:
          command: sudo apt update && sudo apt install yarn
      - run:
          command: docker-compose up --build -d
      - run:
          command: cd frontend && yarn install --frozon-lockfile && ls
      - run:
          command: cd backend && yarn install --frozon-lockfile && ls
      - run:
          command: docker-compose up -d
      - run:
          command: docker-compose exec frontend yarn test --watchAll=false
      - run:
          command: docker-compose exec backend yarn test --watchAll=false
      - run:
          command: docker-compose down
