version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          command: apt-get update && apt-get install sudo curl docker docker-compose yarn
      - run:
          command: docker-compose up --build -d
      - run:
          command: cd frontend && yarn install --frozon-lockfile && ls
      - run:
          command: cd backend && yarn install --frozon-lockfile && ls
      - run:
          command: docker-compose up -d
      - run:
          command: docker-compose exec frontend yarn test --watchAll=false
      - run:
          command: docker-compose exec backend yarn test --watchAll=false
      - run:
          command: docker-compose down
